### ISSUE TITLE
Pls update for fedora 35

### ISSUE THREAD

**Issue by connor-craig** [pentesterwtf/ansible-desktop#27]

**Comment by connor-craig** [comment]
@unsubtleguy pls respond

**Comment by unsubtleguy** [comment]
Looking into it - I'll update tests and see how that goes against Fedora 35, hopefully it's not too much effort

**Comment by unsubtleguy** [comment]
Hey,

This now supports Fedora 35 as per https://github.com/pentesterwtf/ansible-desktop/pull/28
